services:
  - name: extra-ed-db
    plan: starter
    env: 
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: POSTGRES_DB
        value: extra-ed-db
    source:
      type: dockerfile
      buildCommand: docker build -t extra-ed-db .
      envVars:
        - key: DATABASE_URL
          fromService: extra-ed-db
    ports:
      - 5432

  - name: vectordb
    plan: starter
    env:
      - key: POSTGRES_DB
        value: pgvector-db
      - key: POSTGRES_USER
        value: pgvector
      - key: POSTGRES_PASSWORD
        value: admin
    source:
      type: dockerfile
      buildCommand: docker build -t vectordb .
      envVars:
        - key: DATABASE_URL
          fromService: vectordb
    ports:
      - 5434

  - name: extra-ed-app-api
    plan: starter
    source:
      type: dockerfile
      buildCommand: docker build -t extra-ed-app-api .
      dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService: extra-ed-db
    ports:
      - 3000

  - name: pgadmin
    plan: starter
    env:
      - key: PGADMIN_DEFAULT_EMAIL
        value: naomdebele002@gmail.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: 1234567890
    source:
      type: dockerfile
      buildCommand: docker build -t pgadmin .
      dockerfilePath: Dockerfile
    ports:
      - 8888
